version: '3.8'

services:
  bitcoin-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bitcoin-monitor
    volumes:
      - ./:/app
      - ./data:/app/data
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    command: python MCP.client.py MCP.server.py
    # For interactive mode:
    stdin_open: true
    tty: true