---
- name: Run Python Page
  hosts: localhost
  connection: local

  vars:
    page_title: "ML Model Training and Evaluation"
    output_path: "index.html"
    author: "Likhon Gomes"

  tasks:
    - name: Clone ML Model from Github
      ansible.builtin.git:
        repo: https://github.com/likhongomes/Comparative-Analysis-of-RNN-Architectures-for-Sentiment-Classification.git
        dest: ml_model

    # - name: Install Python dependencies
    #   ansible.builtin.pip:
    #     requirements: ml_model/requirements.txt

    - name: Run Python Code to train model
      ansible.builtin.command: python ml_model/train.py --architecture rnn --activation relu --optimizer adam --seq_len 50 --epochs 5 --grad_clip_enable --data_dir ml_model/data
      register: python_train_output

    - name: Python train output
      ansible.builtin.debug:
        msg: "{{ python_train_output }}"

    - name: Run Python Code to evaluate model
      ansible.builtin.command: python ml_model/evaluate.py
      register: python_evaluate_output

    - name: Python evaluate output
      ansible.builtin.debug:
        msg: "{{ python_evaluate_output }}"