version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.7.3
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./bitcoin_utils.py:/opt/airflow/bitcoin_utils.py
      - ${USERPROFILE}/.aws:/home/airflow/.aws
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.7.3
    depends_on:
      - airflow-webserver
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./bitcoin_utils.py:/opt/airflow/bitcoin_utils.py
      - ${USERPROFILE}/.aws:/home/airflow/.aws
    command: scheduler

  airflow-init:
    image: apache/airflow:2.7.3
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - ${USERPROFILE}/.aws:/home/airflow/.aws
    command: >
      bash -c "airflow db init &&
      airflow users create
      --username ${AIRFLOW_ADMIN_USERNAME}
      --password ${AIRFLOW_ADMIN_PASSWORD}
      --firstname admin
      --lastname admin
      --role Admin
      --email ${AIRFLOW_ADMIN_EMAIL}"

volumes:
  postgres-db-volume:
