# Copy one of the Dockerfile style and customize it:
# - class_project/project_template/Dockerfile.python_slim
# - class_project/project_template/Dockerfile.ubuntu
# - class_project/project_template/Dockerfile.uv
