{
 "title": "User Behavior Overview",
 "time": { "from": "2019-09-30T00:11:09.234Z", "to": "2019-10-21T10:34:13.842Z" },
 "panels": [
  {
   "title": "Conversion Rate Over Time",
   "type": "timeseries",
   "description": "This panel answers:\n“At which stage do users drop off before making a purchase?”",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfHour(session_start) AS time,\n    count() AS sessions,\n    sum(has_purchase_in_session) AS purchase_sessions\nFROM session_outcomes\nGROUP BY time\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Event Type Distribution",
   "type": "barchart",
   "description": "This panel answers:\n“What actions do users mostly perform on the platform?”",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    event_type,\n    count() AS event_count\nFROM events_typed\nGROUP BY event_type\nORDER BY event_count DESC;"
    }
   ]
  },
  {
   "title": "Hourly Funnel Trend",
   "type": "timeseries",
   "description": "This panel answers:\n“How do user actions (views, carts, purchases) vary over time?”",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    event_hour AS time,\n    views,\n    carts,\n    purchases\nFROM hourly_funnel\nORDER BY event_hour;"
    }
   ]
  }
 ]
}