version: '3.8'

services:
  jupyter-lean4:
    build: .
    container_name: jupyter-lean4
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/workspace
    environment:
      - JUPYTER_ENABLE_LAB=yes
    restart: unless-stopped
