[tool.poetry]
name = "amp"
version = "0.1.0"
description = ""
authors = ["GP Saggese <gp@kaizen-tech.io>"]

[tool.poetry.dependencies]
async_solipsism = ">= 0.3"
boto3 = "*"
# It is better to up the version manually for CCXT.
ccxt = "4.2.13"
# This constraint is needed because 3.4.8 seems to fail.
cryptography = "<= 3.4.7"
gspread_pandas = "*"
invoke = "*"
joblib = "*"
jsonpickle = "*"
jupyter = "*"
jupytext = "*"
lxml = "*"
matplotlib = "*"
moto = "*"
networkx = "*"
numpy = "*"
pandas = ">= 2.1.1"
psutil = "*"
psycopg2-binary = "*"
pyarrow = ">=15.0.0"
pygraphviz = "*"
python = ">= 3.12"
pytest = "*"
pytest-cov = "*"
pytest-instafail = "*"
pytest-rerunfailures = "*"
pytest-timeout = "*"
pytest-xdist = "*"
python-dotenv = "*"
pywavelets = "*"
requests = "*"
# TODO(Juraj): s3fs needs to be frozen #CmTask10054.
#s3fs = "2024.9.0" # broken
s3fs = "0.4.2" # working
#s3fs = "*"
seaborn = "*"
scikit-learn = "*"
statsmodels = "*"
# This is needed for `pandas.read_sql()`.
SQLAlchemy = "*"
tqdm = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
