site_name: Helpers docs
#site_url: https://mydomain.org/mysite
theme:
  name: material
  palette:
    primary: black
    accent: cyan
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    #- navigation.tabs
    #- navigation.top
    - content.action.edit  # This shows the "Edit this page" link
docs_dir: tmp.mkdocs
# Helps render images and other assets correctly.
use_directory_urls: false
# The search plugin is enabled by default
# but if we specify plugins, we need to include it
# explicitly.
plugins:
  - search
markdown_extensions:
  - toc:
      permalink: "#"
      baselevel: 2
      separator: "_"
extra_css:
  - styles/styles.css
