# .github/workflows/hello.yml

name: Hello World

on:
  push:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checking tree
        run: tree

      - name: Checking ls
        run: ls class_project/data605/Spring2026/projects/UmdTask405_-DATA605_Spring2026_Ansible_Deployment/

      - name: Install Ansible & lint
        run: pip install ansible ansible-lint

      - name: Run ansible-lint
        run: ansible-lint class_project/data605/Spring2026/projects/UmdTask405_-DATA605_Spring2026_Ansible_Deployment/playbook.yaml

      - name: Run ansible-lint
        run: ansible-playbook class_project/data605/Spring2026/projects/UmdTask405_-DATA605_Spring2026_Ansible_Deployment/playbook.yaml

      - name: Upload HTML as artifact
        uses: actions/upload-artifact@v4
        with:
          name: webpage
          path: index.html

      - name: Echo hello world
        run: echo "Hello, World!"

      - name: Checking tree
        run: tree
