# .github/workflows/hello.yml

name: Hello World

on:
  push:
  workflow_dispatch:

jobs:
  hello:
    runs-on: alpine/ansible:2.20.0
    steps:
      # - name: Install Ansible & lint
      #   run: pip install ansible ansible-lint

      - name: Run ansible-lint
        run: ansible-lint playbook.yml

      - name: Echo hello world
        run: echo "Hello, World!"